import db from '../config/database.js';
import path from 'path';

export const uploadVideo = (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No video file provided' });
  }

  const { originalname, filename, mimetype, size, path: uploadPath } = req.file;
  // Use the ID generated by nanoid in the filename
  const id = path.parse(filename).name;

  const query = `INSERT INTO videos (id, original_name, saved_name, mime_type, size, upload_path) VALUES (?, ?, ?, ?, ?, ?)`;
  
  db.run(query, [id, originalname, filename, mimetype, size, uploadPath], function(err) {
    if (err) {
      console.error('Database error:', err);
      return res.status(500).json({ error: 'Failed to save video metadata' });
    }
    
    res.status(201).json({
      message: 'Video uploaded successfully',
      video: {
        id,
        original_name: originalname,
        saved_name: filename,
        mime_type: mimetype,
        size,
        upload_path: uploadPath
      }
    });
  });
};

export const getAllVideos = (req, res) => {
  const query = `SELECT * FROM videos ORDER BY created_at DESC`;
  db.all(query, [], (err, rows) => {
    if (err) {
      console.error('Database error:', err);
      return res.status(500).json({ error: 'Failed to retrieve videos' });
    }
    res.json(rows);
  });
};

export const getVideoById = (req, res) => {
  const { id } = req.params;
  const query = `SELECT * FROM videos WHERE id = ?`;
  
  db.get(query, [id], (err, row) => {
    if (err) {
      console.error('Database error:', err);
      return res.status(500).json({ error: 'Failed to retrieve video metadata' });
    }
    if (!row) {
      return res.status(404).json({ error: 'Video not found' });
    }
    res.json(row);
  });
};
